config/routes.rb
Rails.application.routes.draw do

  root 'portfolio#index'
  get 'about' => 'about#index'
  get 'dashboard' => 'dashboard#index'
  
  devise_for :user, :controllers => { registrations: 'registrations' }

  resources :photos
  
  match 'contact', to: 'contact#new', via: :get
  match 'contact', to: 'contact#create', via: :post

  

end

app/models/message.rb
class Message

  include ActiveModel::Validations
  include ActiveModel::Conversion
  extend ActiveModel::Naming

  attr_accessor :name, :email, :phone, :event_date, :subject, :body

  validates :name, 
            :email, 
            :subject, 
            :body, 
            :presence => true
  validates :email, 
            :format => /\A[\w+\-.]+@[a-z\d\-]+(?:\.[a-z\d\-]+)*\.[a-z]+\z/i, 
            :presence => true
  
  def initialize(attributes = {})
    attributes.each do |name, value|
      send("#{name}=", value)
    end
  end

  def persisted?
    false
  end

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :image, {
      :styles => {thumb: "x100", small: "x200", medium: "x400", large: "x800", giant: "x1000"},
      :convert_options => { thumb: "-quality 70 -strip", small: "-quality 70 -strip", medium: "-quality 70 -strip", large: "-quality 70 -strip", giant: "-quality 70 -strip" }
    }
  validates :image, 
            presence: true
            
  validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png", "image/gif"] }
  
  before_post_process :check_file_size

  def check_file_size
    valid?
    errors[:image_file_size].blank?
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
      @title = "About"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    
  def hide_from_unauthenticated
    not_found unless user_signed_in?
  end

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  
  def new
      @message = Message.new
  end

  def create
    @message = Message.new(params[:message])
    
    if @message.valid?
      NotificationsMailer.new_message(@message).deliver
      flash[:notice] = "Message was successfully sent."
      redirect_to root_path
    else
      flash.now.alert = "Please fill all fields."
      render :new
    end
  end
  
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  
  before_action :hide_from_unauthenticated
  
  def index
    @title = "Dashboard"
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    hide_from_unauthenticated
    @photos = Photo.all
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
     hide_from_unauthenticated
  end

  # GET /photos/new
  def new
    hide_from_unauthenticated
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
    hide_from_unauthenticated
  end

  # POST /photos
  # POST /photos.json
  def create
    hide_from_unauthenticated
    @photo = Photo.new(photo_params)

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    hide_from_unauthenticated
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    hide_from_unauthenticated
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo
      @photo = Photo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_params
      params.require(:photo).permit(:image, :show_on_slideshow, :show_on_gallery, :description)
    end
end

app/controllers/portfolio_controller.rb
class PortfolioController < ApplicationController
  def index
      @photos = Photo.all
      @gallery_photos = Photo.where(show_on_gallery: true)
      @slideshow_photos = Photo.where(show_on_slideshow: true)
      @title = "Portfolio"
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  
  before_action :hide_from_unauthenticated, :except => [:sign_in]
  
  private
 
  def sign_up_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
 
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  #Return a title on a per-page basis
    def title
      base_title = "Kyle Falconer Photography"
      if @title.nil?
        base_title
      else
        "#{@title} | #{base_title}"
      end
    end
  
    def masthead_logo
      link_to image_tag("kf-photography-logo.png", :alt => "Kyle Falconer Photography", :width => 300, :height => 88),
      	root_path,
        :class => "pure-u-1 SiteLogo pure-menu-heading"
    end
 
    def orientation(o: @photo.is_landscape)
       (o ? "landscape" : "portrait")
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/dashboard_helper.rb
module DashboardHelper
end

app/helpers/portfolio_helper.rb
module PortfolioHelper
  
end

app/views/about/index.html.erb
<article class="pure-g-r">
	<h1 class="pure-u-1">About</h1>
	<section class="pure-u-1-3">
		<h2>Services</h2>
		<p>I am available to shoot various events, with an emphasis on wedding and landscape photography. If you are interested in booking me for your event, please <%= link_to "contact me", contact_path %>. I am currently located in Springfield, MO and am willing to travel.</p>
	</section>
	<section class="pure-u-1-3">
		<h2>Kyle Falconer</h2>
		<p>I grew up all over the country, and spent several years in each California, Washington, Texas, and Missouri. I am currently studying Computer Science at Missouri State University and am set to graduate in December, 2014. If you are interested in learning more about me as a programmer, my other website is <a href="http://www.kylefalconercodes.com/">Kyle Falconer Codes</a>.</p>
	</section>
	<aside class="pure-u-2-3"><%= image_tag("Kyle_portrait.jpg", :alt => "Kyle Falconer", :class => "pure-img") %></aside>
	<section class="pure-u-2-3">
		<h2>Photography Background</h2>
		<p>I had always been curious about photography and dabbled with it casually in the form of disposable cameras and whatever film camera I could get my hands on. I was largely limited by film and development costs.</p>
		<p>My curiosity for photography sparked to a flame in 2005 when I took Photography 101 at Ventura Community College. It was for that class that I purchased my first SLR camera, a Canon EOS 1 with the 50mm f/1.8 ("nifty fifty") lens. I learned about the light meter, what the aperture and shutter do, composition, dark room processing and print making. I found that I knew so little and wanted to learn more. A whole world of light and shadow was opening before me.</p>
		<p>While I continued to explore photography as a hobby, my journey as a professional photographer did not start until years later. As my skills began to outgrow my gear, I began upgrading my equipment and my photos started getting noticed. Eventually, I was approached by people who asked me if I could photograph their weddings. Having completed these assignments, I am confident to do more.</p>
		<p>In the past two years alone, I have taken over 17,000 photos with my DSLR camera. I took nearly 5,000 of those during a month-long trip to India, where I fell in love with the people, the land, and photography as a craft. Having now taken so many pictures, I completely agree with Henri Cartier-Bresson when he said "The first 10,000 photos are your worst."</p>
	</section>
	<section class="pure-u-2-3">
		<h2>The Site</h2>
		<p>This web page was made with Ruby on Rails and is hosted on an nginx webserver running on Ubuntu 12.04 through Digital Ocean. Those who are curious can inspect <a href="https://github.com/netinept/Photography" target="_blank">the source code on GitHub</a>. If you want to contribute, feel free to submit a pull request. The site is under the Apache 2.0 license, so if you like what I've created here and need one like it, feel free to <a href="https://github.com/netinept/Photography" target ="_blank">fork me on GitHub</a>.</p>
	</section>
	
</article>

app/views/contact/new.html.erb
<article class="pure-g-r">
	<h1 class="pure-u-1">Contact</h1>
	<section class="pure-u-1">
<%= form_for @message, :url => contact_path, :html => {:class => 'pure-form pure-form-stacked' } do |form|  %>
   
  <% if @message.errors.any? %>
    <div class="error pure-u-1">
      <h2><%= pluralize(@message.errors.count, "error") %> prevented the form from being submitted:</h2>

      <ul>
      <% @message.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  
  <fieldset class="fields">
    <div class="field">
      <%= form.label :name %>
      <%= form.text_field :name, :class => "pure-input-1-3" %>
    </div>
    
    <div class="field">
      <%= form.label :email %>
      <%= form.text_field :email, :class => "pure-input-1-3" %>
    </div>
    <div class="field">
      <%= form.label :phone %>
      <%= form.telephone_field :phone, :class => "pure-input-1-3" %>
    </div>
    <div class="field">
      <%= form.label :event_date %>
      <%= form.date_field :event_date, :class => "pure-input-1-3" %>
    </div>
    <div class="field">
      <%= form.label :subject %>
      <%= form.text_field :subject, :class => "pure-input-1-3" %>
    </div>
    
    <div class="field">
      <%= form.label :body %>
      <%= form.text_area :body, :class => "pure-input-2-3" %>
    </div>
  </fieldset>
  
  <fieldset class="actions">
    <%= form.submit "Send", :class => "pure-button pure-button-primary" %>
  </fieldset>
<% end %>

	</section>
</article>

app/views/dashboard/index.html.erb
<article class="pure-g-r">
	<h1 class="pure-u-1">Dashboard</h1>
	<section class="pure-u-1">
    	<ul>
			<li><%= link_to "Manage Photos", photos_path %></li>
			<li><%= link_to "Manage User", edit_user_registration_path %></li>
		</ul>
	</section>
</article>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title><%= title %></title>
	<meta name=viewport content="width=device-width, initial-scale=1">
	<link rel="shortcut icon" type="image/x-icon" href="favicon.ico"/>
	<%= csrf_meta_tags %>
	<!--[if lt IE 9]>
	  <%= javascript_include_tag 'html5shiv-printshiv' %>
	<![endif]-->
    <%= javascript_include_tag 'application' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
  </head>
  <body>
	  <header class="pure-g-r">
		  <!-- <p class="pure-u-1 SiteLogo pure-menu-heading">Kyle Falconer Photography</p> -->
		  <%= masthead_logo %>
		  <nav id="site_nav" class="pure-u-1 pure-menu pure-menu-open pure-menu-horizontal">
			  <ul>
				  <li><%= link_to "Portfolio", root_path %></li>
				  <li><%= link_to "About", about_path %></li>
				  <li><%= link_to "Contact", contact_path %></li>
			  </ul>
		  </nav>
		  
		  <% if user_signed_in? %>
		  <nav id="user_controls" class="pure-u-1">
		  	<p>Signed in as <%= current_user.name %>.</p>
		  	<ul>
		  		<li><%= link_to "Sign out", destroy_user_session_path, :method => :delete  %></li>
		  		<li><%= link_to "Dashboard", dashboard_path %></li>
		  	</ul>
	  	  </nav>
		  <% end %>
		  
		  <% if flash[:notice] %>
		  <div class="notice pure-u-1"><%= flash[:notice] %></div>
		  <% end %>
	  </header>

	  <%= yield %>
	  <% if false %>
	  <%= debug(params) if Rails.env.development? %>
	  <% end%>

	  <footer class="pure-g-r">
		  <section class="pure-u-1">
			 <p>&copy; 2014 Kyle Falconer</p>
		  </section>
	  </footer>

	  <script>
	  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
	  ga('create', 'UA-51236811-1', 'kylefalconer.photography');
  	  ga('require', 'displayfeatures');
	  ga('send', 'pageview');
	  </script>

  </body>
</html> 

app/views/photos/_form.html.erb
<%= form_for @photo, :html => { :multipart => true } do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, "error") %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  

 <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
     <%= f.label :description %><br>
     <%= f.text_field :description %>
   </div>
   
  <div class="field">
     <%= f.label :show_on_slideshow %><br>
     <%= f.check_box :show_on_slideshow %>
   </div>
    
    <div class="field">
       <%= f.label :show_on_gallery %><br>
       <%= f.check_box :show_on_gallery %>
     </div>
	
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/photos/edit.html.erb
<article class="pure-g-r">
	<h1 class="pure-u-1">Editing photo</h1>
	<section class="pure-u-1">

		<%= image_tag @photo.image.url(:large) %>
		<%= render 'form' %>

		<%= link_to 'Show', @photo %> |
		<%= link_to 'Back', photos_path %>
	</section>
</article>

app/views/photos/index.html.erb
<article class="pure-g-r">
	<p class="pure-u-1">
		<%= link_to 'New Photo', new_photo_path %>
	</p>
</article>

<article class="pure-g-r">
	<h1 class="pure-u-1">Portfolio</h1>
	<section class="pure-u-1 gallery-wrapper ">
    <% @photos.each do |photo| %>
		<div class="photo-wrapper">
			<%= link_to image_tag( photo.image.url(:small),	:data => {
				:orientation => (photo.is_landscape ? "landscape" : "portrait")
				}), 
				edit_photo_path(photo), 
				class: "fancybox", 
				"data-fancybox-group" => "gallery" %>

			<span class="controls">
				<%= link_to 'Show', photo %><br/>
				<%= link_to 'Edit', edit_photo_path(photo) %><br/>
				<%= link_to 'Destroy', photo, method: :delete, data: { confirm: 'Are you sure?' } %>
			</span>

		</div>
	<% end %>
	</section>
</article>

app/views/photos/new.html.erb
<article class="pure-g-r">
	<h1 class="pure-u-1">New photo</h1>
	<section class="pure-u-1">

		<%= render 'form' %>

		<%= link_to 'Back', photos_path %>

	</section>
</article>

app/views/photos/show.html.erb
<article class="pure-g-r">
	<section class="pure-u-1">
		
		<p id="notice"><%= notice %></p>
		
		<%= link_to 'Back', photos_path %>
		<%= link_to 'Edit', edit_photo_path(@photo) %>
		

		<div class="photo-wrapper">
			<%= image_tag @photo.image.url(:large) %>

			<ul class="meta">
				<li>Description: <%= @photo.description %></li>
				<li>Orientation: <%= orientation :o => @photo.is_landscape %></li>
				<li>Show on slideshow: <%= @photo.show_on_slideshow ? "true" : "false" %></li>
				<li>Show on gallery: <%= @photo.show_on_gallery ? "true" : "false" %></li>
			</ul>
		</div>

	</section>
</article>

app/views/portfolio/index.html.erb
		<div id="wedding-carousel" class="carousel slide" data-ride="carousel">
			<!-- Indicators
			<ol class="carousel-indicators">
  			  <% @slideshow_photos.each.with_index do |photo, i| %>
			  <% if photo.show_on_slideshow %>
			  <li data-target="#wedding-carousel" data-slide-to="<%= i %>" class="<%= i == 0 ? ' active' : '' %>" ></li>
  			  <% end %>
			  <% end %>
	 	   </ol> -->

	 	  <!-- Wrapper for slides -->
		  <div class="carousel-inner">
			  <% @slideshow_photos.each.with_index do |photo, i| %>
			  <% if photo.show_on_slideshow %>
			  <div class="item<%= i == 0 ? " active" : "" %> center-cropped" style="background-image: url('<%= photo.image.url(:large) %>');">
				  <%= image_tag( photo.image.url(:large),	:data => {
					  :orientation => (orientation :o => photo.is_landscape)
					  })%>
				  <!--<div class="carousel-caption">
					  <%= photo.description %>
				  </div> -->
			  </div>
			  <% end %>			  
			  <% end %>
		  </div>
		  
		  <!-- Controls
		  <a class="left carousel-control" href="#wedding-carousel" data-slide="prev">
			  <span class="glyphicon glyphicon-chevron-left"></span>
		  </a>
		  <a class="right carousel-control" href="#wedding-carousel" data-slide="next">
			  <span class="glyphicon glyphicon-chevron-right"></span>
		  </a> -->
	  </div>
	  
<article class="pure-g-r">	
	<section class="pure-u-1 gallery-wrapper ">
    <% @gallery_photos.each do |photo| %>
		<div class="photo-wrapper">				
			<%= link_to image_tag( photo.image.url(:medium),	:data => {
						:orientation => (orientation :o => photo.is_landscape)
						}), 
						photo.image.url(:large), 
						class: "fancybox pure-img", 
						"data-fancybox-group" => "gallery" %>
		</div>
	<% end %>
	</section>
</article>